wigner_include = include_directories(['atomic/wignerSymbols'])

atomic_include = include_directories(['atomic', 'atomic/numerics', 'atomic/struct', 'common'])
plasma_include = include_directories(['plasma', 'plasma/numerics', 'plasma/struct', 'common'])
display_include = include_directories('display')
common_include = include_directories('common', 'common/nlohmann')

# subdir('atomic')
# subdir('plasma')
